import pandas as pd
column_types = {   'avg_online_minutes': 'float32',
    'bd_barrack_level': 'uint8',
    'bd_dolmen_level': 'uint8',
    'bd_guest_cavern_level': 'uint8',
    'bd_hall_of_war_level': 'uint8',
    'bd_healing_lodge_level': 'uint8',
    'bd_healing_spring_level': 'uint8',
    'bd_hero_gacha_level': 'uint8',
    'bd_hero_pve_level': 'uint8',
    'bd_hero_strengthen_level': 'uint8',
    'bd_magic_coin_tree_level': 'uint8',
    'bd_market_level': 'uint8',
    'bd_outpost_portal_level': 'uint8',
    'bd_stronghold_level': 'uint8',
    'bd_training_hut_level': 'uint8',
    'bd_warehouse_level': 'uint8',
    'bd_watchtower_level': 'uint8',
    'building_acceleration_add_value': 'uint32',
    'building_acceleration_reduce_value': 'uint32',
    'cavalry_add_value': 'uint32',
    'cavalry_reduce_value': 'uint32',
    'general_acceleration_add_value': 'uint32',
    'general_acceleration_reduce_value': 'uint32',
    'infantry_add_value': 'uint32',
    'infantry_reduce_value': 'uint32',
    'ivory_add_value': 'float32',
    'ivory_reduce_value': 'float32',
    'magic_add_value': 'float32',
    'magic_reduce_value': 'float32',
    'meat_add_value': 'float32',
    'meat_reduce_value': 'float32',
    'pay_count': 'uint8',
    'pay_price': 'float32',
    'prediction_pay_price': 'float32',
    'pve_battle_count': 'uint16',
    'pve_lanch_count': 'uint16',
    'pve_win_count': 'uint16',
    'pvp_battle_count': 'uint16',
    'pvp_lanch_count': 'uint16',
    'pvp_win_count': 'uint16',
    'reaserch_acceleration_add_value': 'uint32',
    'reaserch_acceleration_reduce_value': 'uint32',
    'shaman_add_value': 'uint32',
    'shaman_reduce_value': 'uint32',
    'sr_alliance_march_speed_level': 'uint8',
    'sr_cavalry_atk_level': 'uint8',
    'sr_cavalry_def_level': 'uint8',
    'sr_cavalry_hp_level': 'uint8',
    'sr_cavalry_tier_2_level': 'uint8',
    'sr_cavalry_tier_3_level': 'uint8',
    'sr_cavalry_tier_4_level': 'uint8',
    'sr_construction_speed_level': 'uint8',
    'sr_gathering_hunter_buff_level': 'uint8',
    'sr_gathering_march_speed_level': 'uint8',
    'sr_guest_troop_capacity_level': 'uint8',
    'sr_healing_space_level': 'uint8',
    'sr_healing_speed_level': 'uint8',
    'sr_hide_storage_level': 'uint8',
    'sr_infantry_atk_level': 'uint8',
    'sr_infantry_def_level': 'uint8',
    'sr_infantry_hp_level': 'uint8',
    'sr_infantry_tier_2_level': 'uint8',
    'sr_infantry_tier_3_level': 'uint8',
    'sr_infantry_tier_4_level': 'uint8',
    'sr_march_size_level': 'uint8',
    'sr_outpost_durability_level': 'uint8',
    'sr_outpost_tier_2_level': 'uint8',
    'sr_outpost_tier_3_level': 'uint8',
    'sr_outpost_tier_4_level': 'uint8',
    'sr_pvp_march_speed_level': 'uint8',
    'sr_rss_a_gather_level': 'uint8',
    'sr_rss_a_prod_levell': 'uint8',
    'sr_rss_b_gather_level': 'uint8',
    'sr_rss_b_prod_level': 'uint8',
    'sr_rss_c_gather_level': 'uint8',
    'sr_rss_c_prod_level': 'uint8',
    'sr_rss_d_gather_level': 'uint8',
    'sr_rss_d_prod_level': 'uint8',
    'sr_rss_e_gather_level': 'uint8',
    'sr_rss_e_prod_level': 'uint8',
    'sr_rss_help_bonus_level': 'uint8',
    'sr_scout_level': 'uint8',
    'sr_shaman_atk_level': 'uint8',
    'sr_shaman_def_level': 'uint8',
    'sr_shaman_hp_level': 'uint8',
    'sr_shaman_tier_2_level': 'uint8',
    'sr_shaman_tier_3_level': 'uint8',
    'sr_shaman_tier_4_level': 'uint8',
    'sr_training_speed_level': 'uint8',
    'sr_troop_attack_level': 'uint8',
    'sr_troop_consumption_level': 'uint8',
    'sr_troop_defense_level': 'uint8',
    'sr_troop_load_level': 'uint8',
    'stone_add_value': 'float32',
    'stone_reduce_value': 'float32',
    'training_acceleration_add_value': 'uint32',
    'training_acceleration_reduce_value': 'uint32',
    'treatment_acceleraion_add_value': 'uint16',
    'treatment_acceleration_reduce_value': 'uint16',
    'user_id': 'uint32',
    'wood_add_value': 'float32',
    'wood_reduce_value': 'float32',
    'wound_cavalry_add_value': 'uint32',
    'wound_cavalry_reduce_value': 'uint32',
    'wound_infantry_add_value': 'uint32',
    'wound_infantry_reduce_value': 'uint32',
    'wound_shaman_add_value': 'uint32',
    'wound_shaman_reduce_value': 'uint32'}
def load_data(filename):


    # usecols ={   
    # 'avg_online_minutes',
    # 'bd_barrack_level',
    # 'bd_dolmen_level',
    # 'bd_guest_cavern_level',
    # 'bd_hall_of_war_level',
    # 'bd_healing_lodge_level',
    # 'bd_healing_spring_level',
    # 'bd_hero_gacha_level',
    # 'bd_hero_pve_level',
    # 'bd_hero_strengthen_level',
    # 'bd_magic_coin_tree_level',
    # 'bd_market_level',
    # 'bd_outpost_portal_level',
    # 'bd_stronghold_level',
    # 'bd_training_hut_level',
    # 'bd_warehouse_level',
    # 'bd_watchtower_level',
    # 'building_acceleration_add_value',
    # 'building_acceleration_reduce_value',
    # 'cavalry_add_value',
    # 'cavalry_reduce_value',
    # 'general_acceleration_add_value',
    # 'general_acceleration_reduce_value',
    # 'infantry_add_value',
    # 'infantry_reduce_value',
    # 'ivory_add_value',
    # 'ivory_reduce_value',
    # 'magic_add_value',
    # 'magic_reduce_value',
    # 'meat_add_value',
    # 'meat_reduce_value',
    # # 'pay_count',
    # # 'pay_price',
    # # 'prediction_pay_price',
    # 'pve_battle_count',
    # 'pve_lanch_count',
    # 'pve_win_count',
    # 'pvp_battle_count',
    # 'pvp_lanch_count',
    # 'pvp_win_count',
    # 'reaserch_acceleration_add_value',
    # 'reaserch_acceleration_reduce_value',
    # 'shaman_add_value',
    # 'shaman_reduce_value',
    # 'sr_alliance_march_speed_level',
    # 'sr_cavalry_atk_level',
    # 'sr_cavalry_def_level',
    # 'sr_cavalry_hp_level',
    # 'sr_cavalry_tier_2_level',
    # 'sr_cavalry_tier_3_level',
    # 'sr_cavalry_tier_4_level',
    # 'sr_construction_speed_level',
    # 'sr_gathering_hunter_buff_level',
    # 'sr_gathering_march_speed_level',
    # 'sr_guest_troop_capacity_level',
    # 'sr_healing_space_level',
    # 'sr_healing_speed_level',
    # 'sr_hide_storage_level',
    # 'sr_infantry_atk_level',
    # 'sr_infantry_def_level',
    # 'sr_infantry_hp_level',
    # 'sr_infantry_tier_2_level',
    # 'sr_infantry_tier_3_level',
    # 'sr_infantry_tier_4_level',
    # 'sr_march_size_level',
    # 'sr_outpost_durability_level',
    # 'sr_outpost_tier_2_level',
    # 'sr_outpost_tier_3_level',
    # 'sr_outpost_tier_4_level',
    # 'sr_pvp_march_speed_level',
    # 'sr_rss_a_gather_level',
    # 'sr_rss_a_prod_levell',
    # 'sr_rss_b_gather_level',
    # 'sr_rss_b_prod_level',
    # 'sr_rss_c_gather_level',
    # 'sr_rss_c_prod_level',
    # 'sr_rss_d_gather_level',
    # 'sr_rss_d_prod_level',
    # 'sr_rss_e_gather_level',
    # 'sr_rss_e_prod_level',
    # 'sr_rss_help_bonus_level',
    # 'sr_scout_level',
    # 'sr_shaman_atk_level',
    # 'sr_shaman_def_level',
    # 'sr_shaman_hp_level',
    # 'sr_shaman_tier_2_level',
    # 'sr_shaman_tier_3_level',
    # 'sr_shaman_tier_4_level',
    # 'sr_training_speed_level',
    # 'sr_troop_attack_level',
    # 'sr_troop_consumption_level',
    # 'sr_troop_defense_level',
    # 'sr_troop_load_level',
    # 'stone_add_value',
    # 'stone_reduce_value',
    # 'training_acceleration_add_value',
    # 'training_acceleration_reduce_value',
    # 'treatment_acceleraion_add_value',
    # 'treatment_acceleration_reduce_value',
    # 'user_id',
    # 'wood_add_value',
    # 'wood_reduce_value',
    # 'wound_cavalry_add_value',
    # 'wound_cavalry_reduce_value',
    # 'wound_infantry_add_value',
    # 'wound_infantry_reduce_value',
    # 'wound_shaman_add_value',
    # 'wound_shaman_reduce_value'
    # }


    
    data =  pd.read_csv(filename, dtype=column_types)
    # data =  pd.read_csv(filename, dtype=column_types, usecols=usecols)
    
    return data

def load_data_test(filename):
    usecols ={   
    'avg_online_minutes',
    'bd_barrack_level',
    'bd_dolmen_level',
    'bd_guest_cavern_level',
    'bd_hall_of_war_level',
    'bd_healing_lodge_level',
    'bd_healing_spring_level',
    'bd_hero_gacha_level',
    'bd_hero_pve_level',
    'bd_hero_strengthen_level',
    'bd_magic_coin_tree_level',
    'bd_market_level',
    'bd_outpost_portal_level',
    'bd_stronghold_level',
    'bd_training_hut_level',
    'bd_warehouse_level',
    'bd_watchtower_level',
    'building_acceleration_add_value',
    'building_acceleration_reduce_value',
    'cavalry_add_value',
    'cavalry_reduce_value',
    'general_acceleration_add_value',
    'general_acceleration_reduce_value',
    'infantry_add_value',
    'infantry_reduce_value',
    'ivory_add_value',
    'ivory_reduce_value',
    'magic_add_value',
    'magic_reduce_value',
    'meat_add_value',
    'meat_reduce_value',
    'pay_count',
    'pay_price',
    # 'prediction_pay_price',
    'pve_battle_count',
    'pve_lanch_count',
    'pve_win_count',
    'pvp_battle_count',
    'pvp_lanch_count',
    'pvp_win_count',
    'reaserch_acceleration_add_value',
    'reaserch_acceleration_reduce_value',
    'shaman_add_value',
    'shaman_reduce_value',
    'sr_alliance_march_speed_level',
    'sr_cavalry_atk_level',
    'sr_cavalry_def_level',
    'sr_cavalry_hp_level',
    'sr_cavalry_tier_2_level',
    'sr_cavalry_tier_3_level',
    'sr_cavalry_tier_4_level',
    'sr_construction_speed_level',
    'sr_gathering_hunter_buff_level',
    'sr_gathering_march_speed_level',
    'sr_guest_troop_capacity_level',
    'sr_healing_space_level',
    'sr_healing_speed_level',
    'sr_hide_storage_level',
    'sr_infantry_atk_level',
    'sr_infantry_def_level',
    'sr_infantry_hp_level',
    'sr_infantry_tier_2_level',
    'sr_infantry_tier_3_level',
    'sr_infantry_tier_4_level',
    'sr_march_size_level',
    'sr_outpost_durability_level',
    'sr_outpost_tier_2_level',
    'sr_outpost_tier_3_level',
    'sr_outpost_tier_4_level',
    'sr_pvp_march_speed_level',
    'sr_rss_a_gather_level',
    'sr_rss_a_prod_levell',
    'sr_rss_b_gather_level',
    'sr_rss_b_prod_level',
    'sr_rss_c_gather_level',
    'sr_rss_c_prod_level',
    'sr_rss_d_gather_level',
    'sr_rss_d_prod_level',
    'sr_rss_e_gather_level',
    'sr_rss_e_prod_level',
    'sr_rss_help_bonus_level',
    'sr_scout_level',
    'sr_shaman_atk_level',
    'sr_shaman_def_level',
    'sr_shaman_hp_level',
    'sr_shaman_tier_2_level',
    'sr_shaman_tier_3_level',
    'sr_shaman_tier_4_level',
    'sr_training_speed_level',
    'sr_troop_attack_level',
    'sr_troop_consumption_level',
    'sr_troop_defense_level',
    'sr_troop_load_level',
    'stone_add_value',
    'stone_reduce_value',
    'training_acceleration_add_value',
    'training_acceleration_reduce_value',
    'treatment_acceleraion_add_value',
    'treatment_acceleration_reduce_value',
    'user_id',
    'wood_add_value',
    'wood_reduce_value',
    'wound_cavalry_add_value',
    'wound_cavalry_reduce_value',
    'wound_infantry_add_value',
    'wound_infantry_reduce_value',
    'wound_shaman_add_value',
    'wound_shaman_reduce_value'
    }

    data =  pd.read_csv(filename, dtype=column_types, usecols=usecols)
    return data 

def mem_usage(pandas_obj):
    if isinstance(pandas_obj, pd.DataFrame):
        usage_b = pandas_obj.memory_usage(deep=True).sum()
    else:
        usage_b = pandas_obj.memory_usage(deep=True)
    usage_mb = usage_b /1024 ** 2
    return "{:03.2f} MB".format(usage_mb)